1.7.10 version 0.29.4
Esteemed-Innovation/Flaxbeards-Steam-Power pull request #524
Opened 2019-11-02 02:35 UTC by Hogan-Dazs

It fixes the following bugs:
* Jetpacks halways have fall damage in multiplayer
* Pyrophobic coatings crash the game when walking on lava in multiplayer

2019-11-04 20:05 UTC, elifoster requested changes
Please remove the irrelevant changes to the codebase, then I will test and re-review this PR. Thank you for your contributions!

2019-11-04 20:05 UTC, elifoster commented on src/main/java/flaxbeard/steamcraft/block/BlockPipe.java
> +           return  this.rayTracer.rayTraceCuboids(new Vector3(start), new Vector3(end), cuboids, new BlockCoord(x, y, z), this);
Irrelevant change with wrong spacing

2019-11-04 20:05 UTC, elifoster commented on src/main/java/flaxbeard/steamcraft/block/BlockSteamcraftOre.java
>          default: //Same as overworld
Irrelevant change

2019-11-04 20:05 UTC, elifoster commented on src/main/java/flaxbeard/steamcraft/integration/ic2/IC2RecipeInput.java
> +    	return Arrays.asList(input);
Irrelevant change

2019-11-04 20:05 UTC, elifoster commented on src/main/java/flaxbeard/steamcraft/integration/tinkers/ModiferSteam.java
> +        if(tool != null && tool.getItem() != null && tool.getItem() instanceof ToolCore) {
Space in between `if` and `(`

2019-11-04 20:05 UTC, elifoster commented on src/main/java/flaxbeard/steamcraft/tile/TileEntityVacuum.java
> +        return  dotProd(apexToXVect, axisVect)
Irrelevant change

2019-11-04 20:05 UTC, elifoster commented on src/main/java/flaxbeard/steamcraft/tile/TileEntitySteamGauge.java
> +        return (int) (15 * (100 * ((double) getPressure() * 0.01D)));
Irrelevant change

2019-11-04 20:05 UTC, elifoster commented on src/main/java/flaxbeard/steamcraft/tile/TileEntityCrucible.java
> -        int out = (int) ((double) 15 * (((double) getFill() / 90D)));
Irrelevant change

2019-11-04 20:05 UTC, elifoster commented on src/main/java/flaxbeard/steamcraft/integration/tinkers/ModiferSteam.java
>      protected boolean canModify(ItemStack tool, ItemStack[] input) {
Irrelevant change

2019-11-04 20:33 UTC, Hogan-Dazs commented
All those changes came from merging the source from the latest release with the branch, if you want I can remove them, but I just wanted to note that they are a result of discrepancies between the 1.7 branch and the 0.29.3 release, not changes I made.

2019-11-04 20:45 UTC, elifoster commented
Oh, okay. Hold off on that then, I'm going to try to figure out why those commits are not in the 1.7 branch.

2019-11-04 20:52 UTC, elifoster commented
Okay, the 1.7 branch has been updated to include the missing commits. This was so long ago, I don't remember what happened but somehow all the commits from 0.29.3 disappeared and were only accessible through the 0.29.3 tag. Anyway, if you update your 1.7 branch and fix the merge conflicts it should be fine.

2019-11-05 03:13 UTC, Hogan-Dazs commented
I got it updated

2019-11-05 17:39 UTC, elifoster commented
Cool, will find some time to test it out soon.

2021-09-22 04:03 UTC, closed without merging